[package]
name = "rlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
simplelog = "0.11.1"
sdl2 = { version = "0.35.1", features = ["bundled", "static-link"] }
gl = "0.14.0"